### ISSUE TITLE
Content Safety

### ISSUE THREAD

**Issue by hectoritr** [cboard-org/cboard-ai-engine#23]
Create some Content Safety measures to avoid misuse and potential harmful results. 

https://learn.microsoft.com/en-us/azure/machine-learning/prompt-flow/tools-reference/content-safety-text-tool?view=azureml-api-2

**Comment by Da-PC** [comment]
https://learn.microsoft.com/en-us/azure/ai-studio/concepts/evaluation-metrics-built-in
