### ISSUE TITLE
Fix token limits

### ISSUE THREAD

**Issue by hectoritr** [cboard-org/cboard-ai-engine#26]

**Comment by Da-PC** [comment]
![image](https://github.com/cboard-org/cboard-ai-engine/assets/127154933/25a11166-434c-46b9-ac88-5bbab7838c8d)

I´ve run multiple runs and this the data I´ve gathered. My assumptions are:
    - Max Pictos per request 50.
    
Results:
If we provide a high number of token the Chat get dilusional and add repeated words or garbage, so we need to constrain the token limit. This also helps with security and jailbreaking. 
The growth of token is 4.11x+76.7. I´ll be using 4.5x+80 to accomodate word lenght variation based on the topic of the prompt.

**Comment by Da-PC** [comment]
Final comment, with higher number is still a bit delusional and return more suggestions than requested.

**Comment by tomivm** [comment]
Good! Do you think that #22 is caused by this token limit? If we could return the data before the limit would be better than returning an empty array. Also if this is not possible would be better to throw an Error

**Comment by Da-PC** [comment]
Yes I think this will be solved. But still the Error handling will be good practice.
