### ISSUE TITLE
Avoid use of any on fetchPictogramsURL()

### ISSUE THREAD

**Issue by RodriSanchez1** [cboard-org/cboard-ai-engine#3]
`any` should be replaced with the actual type. Or just be removed if `data` variable is already typed.

_Originally posted by @shayc in https://github.com/cboard-org/cboard-ai-engine/pull/1#discussion_r1504586150_

**Comment by shayc** [comment]
Merged to main: pull request [6](https://github.com/cboard-org/cboard-ai-engine/pull/6)
